spring.application.name=Spring-RAG

server.port=0

spring.ai.vectorstore.qdrant.initialize-schema=true

spring.ai.vectorstore.qdrant.collection-name=GameRules

spring.ai.ollama.base-url=http://localhost:11434

# Specify the local model you pulled
spring.ai.ollama.chat.model=gemma3:4b
spring.ai.ollama.chat.options.model=gemma3:4b

#spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.embedding.options.model=mxbai-embed-large

spring.ai.ollama.embedding.enabled=false

spring.cloud.function.definition=\
  fileSupplier|\
  documentReader|\
  splitter|\
  titleDeterminer|\
  vectorStoreConsumer

file.supplier.directory=D:\\Projects\\documents

file.supplier.filename-regex=.*\.(pdf|docx|txt)

logging.level.org.zalando.logbook: TRACE
logbook.format.style=http