spring.application.name=Spring-AI

spring.ai.ollama.init.pull-model-strategy=never


spring.ai.ollama.base-url=http://localhost:11434

# Specify the local model you pulled
spring.ai.ollama.chat.model=llama3.2:3b

#spring.ai.google.genai.chat.options.model=gemini-2.0-flash

#spring.ai.google.genai.api-key=aa