spring.application.name=Spring-AI

spring.ai.ollama.init.pull-model-strategy=never


spring.ai.ollama.base-url=http://localhost:11434

# Specify the local model you pulled
spring.ai.ollama.chat.model=llama3.2:3b
spring.ai.ollama.chat.options.model=llama3.2:3b

spring.ai.openai.chat.options.top-p=0.8

spring.ai.ollama.chat.options.top-k=4


#spring.ai.google.genai.chat.options.model=gemini-2.0-flash

#spring.ai.google.genai.api-key=aa

logging.level.org.zalando.logbook: TRACE
logbook.format.style=http